name: Check Pending Workflows

permissions:
  contents: read
  actions: read

on:
  workflow_call:

jobs:
  check-pending-workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 125
    steps:
      - name: Check for pending workflows
        uses: ahmadnassri/action-workflow-queue@542658b3a8270cac81ae15d401b0d974732808ac # v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delay: 300000
          timeout: 7200000
